kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: istio-gateway-allow
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          networking/namespace: istio-system