apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: hierarchy
  git:
    repo: ssh://dkassab@google.com@source.developers.google.com:2022/p/prj-bu1-d-boa-gke-ecb0/r/root-config-repo
    branch: master
    auth: ssh
    secretRef:
      name: git-creds
      