apiVersion: v1
data:
  connectionName: cHJqLWJ1MS1kLWJvYS1zcWwtNGY0OTp1cy1lYXN0MTpib2Etc3FsLXVzLWVhc3QxLTNhMmY2OGFi
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  name: cloud-sql-admin
type: Opaque
